# we assemble the skeleton / directory for use in Tartaria
FROM ghcr.io/tartaria-dev/cherries:latest-amd64

# temporary workaround
COPY --from=archlinux:latest / /

# clean existing dots directory
RUN rm -rf /system_files/usr/share/tartaria/cherries/*

# now we repopulate the directory with the new dots
COPY system-dots/ /system_files/usr/share/tartaria/cherries
