# we assemble the skeleton / directory for use in Tartaria
FROM ghcr.io/tartaria-dev/cherries:latest

# clean existing dots directory
RUN rm -rf /system_files/system_dots/*

# now we repopulate the directory with the new dots
COPY system-dots /system_files/system_dots
