FROM archlinux:latest AS builder

# install base packages
RUN pacman -Syu --noconfirm --needed base-devel git sudo
RUN useradd -m builder
RUN echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder

# start working as build user
USER builder
WORKDIR /home/builder

# build yay and prepare package list
RUN git clone https://aur.archlinux.org/yay-bin.git && \
    cd yay-bin && \
    makepkg -si --noconfirm && \
    cd .. && \
    rm -rf yay-bin
COPY --chown=builder:builder system-packages/packages.txt .
RUN mkdir -p /home/builder/packages

# retreive package source and build package from source for each entry in packages.txt
RUN while read -r pkg; do \
    echo "Building $pkg..."; \
    yay -G "$pkg" && \
    cd "$pkg" && \
    makepkg -sr --noconfirm --nocheck && \
    cp *.pkg.tar.zst /home/builder/packages/ && \
    cd .. && \
    rm -rf "$pkg"; \
    done < packages.txt

# dummy install - we'll fetch the maplemono packages from cache
RUN yay -S --noconfirm maplemono-ttf

FROM scratch AS final

# copy over packages
COPY --from=builder /home/builder/packages/ /
COPY --from=builder home/builder/.cache/yay/maplemono/maplemono-nf-cn-unhinted-*-any.pkg.tar.zst /
COPY --from=builder home/builder/.cache/yay/maplemono/maplemono-cn-unhinted-*-any.pkg.tar.zst /
COPY --from=builder home/builder/.cache/yay/maplemono/maplemono-ttf-*-any.pkg.tar.zst /
