# builder image
FROM archlinux:latest AS builder

# install base packages
RUN pacman -Syu --noconfirm --needed base-devel git sudo parallel
RUN useradd -m builder
RUN echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder

# now start working as build user
USER builder
WORKDIR /home/builder

# build yay and prepare package lists
RUN git clone https://aur.archlinux.org/yay-bin.git && \
    cd yay-bin && \
    makepkg -si --noconfirm && \
    cd .. && \
    rm -rf yay-bin
COPY --chown=builder:builder system-packages/ .
RUN mkdir -p /home/builder/mainsys-pkgs /home/builder/subsys-pkgs

# build aur pkgs
RUN bash ./build.sh ./mainsys-pkgs.txt
RUN bash ./build.sh ./subsys-pkgs.txt

# dummy install maplemono - we'll copy the built packages later
RUN yay -S --noconfirm maplemono-ttf

# final image
FROM scratch AS final

# copy mainsys packages
COPY --from=builder /home/builder/mainsys-pkgs/ /mainsys/
COPY --from=builder home/builder/.cache/yay/maplemono/maplemono-nf-cn-unhinted-*-any.pkg.tar.zst /mainsys/
COPY --from=builder home/builder/.cache/yay/maplemono/maplemono-cn-unhinted-*-any.pkg.tar.zst /mainsys/
COPY --from=builder home/builder/.cache/yay/maplemono/maplemono-ttf-*-any.pkg.tar.zst /mainsys/

# copy subsys packages
COPY --from=builder /home/builder/subsys-pkgs/ /subsys/
