# we assemble the skeleton / directory for use in Tartaria
FROM archlinux:latest AS final

# clean existing dots directory
RUN mkdir -p /system_files

# now we repopulate the directory with the new dots
COPY system-dots/ /system_files/
