color0 #12131a
color1 #ffb4ab
color2 #bac4fa
color3 #ecb8ce
color4 #a1d48f
color5 #bac4fa
color6 #ecb8ce
color7 #e2e1ec
color8 #8e909f
color9 #ffb4ab
color10 #bac4fa
color11 #ecb8ce
color12 #a1d48f
color13 #bac4fa
color14 #ecb8ce
color15 #e2e1ec

cursor                #e2e1ec
cursor_text_color     #12131a
background            #12131a
foreground            #e2e1ec
selection_foreground  #c4c5d6
selection_background  #444654
url_color             #a1d48f