QT_QPA_PLATFORM="wayland;xcb"
QT_WAYLAND_DISABLE_WINDOWDECORATION="1"
QT_AUTO_SCREEN_SCALE_FACTOR="1"
QT_QPA_PLATFORMTHEME="qt6ct"

MOZ_ENABLE_WAYLAND="1"
GDK_SCALE="1"
SDL_VIDEODRIVER="wayland"

ELECTRON_ENABLE_WAYLAND="1"
ELECTRON_OZONE_PLATFORM_HINT="wayland"

XCURSOR_THEME="Bibata-Original-Ice"
XCURSOR_SIZE=28

FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0"

BROWSER=/usr/bin/zen-browser
